import { IUserRepository } from '../../../../domain/repositories/IUserRepository';
import { User } from '../../../../domain/entities/user.entity';
import { CreateUserDto } from '../../dtos/user/CreateUser.dto';
import * as bcrypt from 'bcrypt';
import { IStreamRepository } from '../../../../domain/repositories/IStreamRepository';
import { Stream } from '../../../../domain/entities/stream.entity';

export class CreateUserUseCase {
  constructor(
    private readonly userRepository: IUserRepository,
    private readonly streamRepository: IStreamRepository,
  ) {}

  async execute(dto: CreateUserDto): Promise<User> {
    const existingUser = await this.userRepository.findByEmail(dto.email);
    if (existingUser) {
      throw new Error('User with this email already exists.');
    }

    const hashedPassword = await bcrypt.hash(dto.password, 10);

    const user = new User({
      id: '', // ID will be generated by the database
      username: dto.username,
      email: dto.email,
      password: hashedPassword,
      streamKey: '', // Will be generated by the entity
    });

    const createdUser = await this.userRepository.create(user);

    // Create a stream for the new user
    const stream = new Stream({
      id: '', // ID will be generated by the database
      userId: createdUser.id,
      title: `${createdUser.username}'s Stream`,
      description: '',
      isLive: false,
      thumbnailUrl: '',
    });

    await this.streamRepository.create(stream);

    return createdUser;
  }
}